conformance: use the user script to clean up
As the clean process also depends on the implementation, make it more
generic by calling the user script instead of doing it directly in the
main script.
Modify the template script to add a new "clean" argument to clean for
the CI board.

SFL: #21842
Change-Id: I38878f0795a95d04d3b8a84d2721184edc65150d
Signed-off-by: Kévin L'hôpital <kevin.lhopital@savoirfairelinux.com>

diff --git a/launch_gapi_test_app.sh.template b/launch_gapi_test_app.sh.template
--- a/launch_gapi_test_app.sh.template
+++ b/launch_gapi_test_app.sh.template
@@ -33,6 +33,27 @@ launch_app_without_report() {
     -- /etc/cukinia/cukinia /etc/GEISA-API-tests/cukinia.conf
 }
 
+clean_up() {
+    if mountpoint -q /tmp/GAPI-tests/rootfs; then
+        umount /tmp/GAPI-tests/rootfs || {
+            echo -e "Error: Failed to unmount test filesystem on board"
+            exit 1
+        }
+    fi
+    if mountpoint -q /tmp/GAPI-tests/base; then
+        umount /tmp/GAPI-tests/base || {
+            echo -e "Error: Failed to unmount base filesystem on board"
+            exit 1
+        }
+    fi
+    if mountpoint -q /tmp/GAPI-tests/app; then
+        umount /tmp/GAPI-tests/app || {
+            echo -e "Error: Failed to unmount app filesystem on board"
+            exit 1
+        }
+    fi
+}
+
 case "$1" in
     "report")
         echo "Launching gapi_test_app with report configuration..."
@@ -41,6 +62,10 @@ case "$1" in
     "no-report")
         echo "Launching gapi_test_app with no-report configuration..."
         launch_app_without_report
+        ;;
+    "clean")
+        echo "Cleaning up mounted filesystems and temporary directories..."
+        clean_up
         ;;
     *)
         echo "Unknown argument: $1"
